[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "mod_lns"
authors = [{name = "Tom Schmidt"}]
description = "A Modular Large Neighbourhood Search Framework."
requires-python = ">=3.12"
dynamic = ["version"]
dependencies = [
    "importlib_metadata;python_version<'3.12'",
    "clingo>=5.8.0",
    "clingo-dl>=1.5.0",
    "clingcon>=5.2.1",
]
license = { file = "LICENSE" }
readme = "README.md"

[project.optional-dependencies]
format = ["black", "isort", "autoflake"]
lint_pylint = ["pylint"]
typecheck = ["types-setuptools", "mypy"]
test = ["coverage[toml]"]
doc = ["sphinx", "furo", "nbsphinx", "sphinx_copybutton", "myst-parser"]
dev = ["mod_lns[test,typecheck,lint_pylint]"]
full = ["mod_lns[doc]"]

[project.scripts]
mod_lns = "mod_lns.__main__:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools_scm]
version_scheme = "python-simplified-semver"
local_scheme = "no-local-version"

[tool.isort]
profile = "black"
line_length = 120

[tool.black]
line-length = 120

[tool.pylint.format]
max-line-length = 120

[tool.pylint.design]
max-args = 10
max-attributes = 7
max-bool-expr = 5
max-branches = 12
max-locals = 30
max-parents = 7
max-public-methods = 20
max-returns = 10
max-statements = 50
min-public-methods = 1

[tool.pylint.similarities]
ignore-comments = true
ignore-docstrings = true
ignore-imports = true
ignore-signatures = true

[tool.pylint.basic]
argument-rgx = "^[a-z][a-z0-9]*((_[a-z0-9]+)*_?)?$"
variable-rgx = "^[a-z][a-z0-9]*((_[a-z0-9]+)*_?)?$"
good-names = ["_"]

[tool.pylint."messages control"]
disable = ["duplicate-code"]

[tool.coverage.run]
source = ["mod_lns"]
omit = ["*/mod_lns/__main__.py", "tests/*", "*/tests/*"]

[tool.coverage.report]
exclude_also = ["assert", "nocoverage"]
