[metadata]
name = mod_lns
version = 5.0.3
author = Tom Schmidt
author_email = tom.schmidt@uni-potsdam.de
description = Modular Large Neighbourhood Search Framework
long_description = file: README.md
long_description_content_type = text/markdown
license = MIT
url = https://potassco.org/

[options]
packages = find:
package_dir =
    =src
include_package_data = True
install_requires =
    importlib_metadata;python_version<'3.12'
    clingo>=5.8.0
    clingo-dl>=1.5.0
    clingcon>=5.2.1

[options.packages.find]
where = src

[options.extras_require]
format =
    black
    isort
    autoflake
lint_flake8 =
    flake8
    flake8-black
    flake8-isort
lint_pylint =
    pylint
typecheck =
    types-setuptools
    mypy
test =
    coverage
doc =
    sphinx
    furo
    nbsphinx
    sphinx_copybutton
    myst-parser
dev =
    mod_lns[test,typecheck,lint_pylint,lint_flake8]
full =
    mod_lns[doc]

[options.entry_points]
console_scripts =
    mod_lns = mod_lns.__main__:main
