[metadata]
name = large_neighbourhood_search
version = 3.3.4
author = Tom Schmidt
author_email = tom.schmidt@uni-potsdam.de
description = Large Neighbourhood Search
long_description = file: README.md
long_description_content_type = text/markdown
license = MIT
url = https://potassco.org/

[options]
packages = find:
package_dir =
    =src
include_package_data = True
install_requires =
    importlib_metadata;python_version<'3.12'
    clingo>=5.7.0
    clingo-dl>=1.5.0

[options.packages.find]
where = src

[options.extras_require]
format =
    black
    isort
    autoflake
lint_flake8 =
    flake8
    flake8-black
    flake8-isort
lint_pylint =
    pylint
typecheck =
    types-setuptools
    mypy
test =
    coverage
doc =
    sphinx
    furo
    nbsphinx
    sphinx_copybutton
    myst-parser
dev =
    large_neighbourhood_search[test,typecheck,lint_pylint,lint_flake8]
full =
    large_neighbourhood_search[doc]

[options.entry_points]
console_scripts =
    large_neighbourhood_search = large_neighbourhood_search.__main__:main
